# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8de01d1ca5864938309e1381e6ac2c4bdd3fa266bc91383212dc05ace396a3b00c62b4465727be77ae9b8ab9ef79e2f4daff32aa772acb61ec7e168a474613a

test:
  secret_key_base: ea2686b540d872dc7d5cee7549a6e311711466c81cbfdf92256703e83f5c35a4fb0299737d5aa1fe4af117c6e690b732605316ff8c359feec806c90dfb6a9ea0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
